import { Body, Controller, Delete, Get, HttpCode, HttpStatus, Param, Patch, Post, Query, Req } from "@nestjs/common";
import { AudienceTargetType, AudienceType, CompletionStatus } from "@prisma/client";
import { createItemSchema, itemListQuerySchema, updateItemSchema } from "@relay-work/contracts";
import { z } from "zod";
import { ApiError } from "../common/api-error.js";
import { parse } from "../common/zod.js";
import { RelayService } from "./relay.service.js";

type RequestWithUser = { currentUser: { id: string } };
@Controller()
export class RelayController {
  constructor(private readonly relay: RelayService) {}
  private user(request: RequestWithUser) { return request.currentUser.id; }
  private async owner(teamId: string, userId: string) { const member = await this.relay.member(teamId, userId); if (!member.isOwner) throw new ApiError(HttpStatus.FORBIDDEN, "OWNER_REQUIRED", "OWNER만 수행할 수 있습니다."); return member; }
  private async assertAudiences(teamId: string, audiences: Array<{ targetType: AudienceTargetType; targetMemberId?: string; targetRoleId?: string }>, type: AudienceType) {
    if (type === "TEAM") { if (audiences.length) throw new ApiError(HttpStatus.BAD_REQUEST, "INVALID_REQUEST", "팀 전체 전달에는 대상을 지정할 수 없습니다."); return; }
    if (!audiences.length) throw new ApiError(HttpStatus.BAD_REQUEST, "INVALID_REQUEST", "제한 전달에는 최소 한 명 또는 역할을 지정해야 합니다.");
    for (const target of audiences) {
      if (target.targetType === "MEMBER") { if (!target.targetMemberId || target.targetRoleId) throw new ApiError(HttpStatus.BAD_REQUEST, "INVALID_REQUEST", "멤버 대상 형식이 올바르지 않습니다."); const member = await this.relay.db.teamMember.findUnique({ where: { id: target.targetMemberId } }); if (!member || member.teamId !== teamId || !member.isActive) throw new ApiError(HttpStatus.BAD_REQUEST, "RECIPIENT_NOT_IN_TEAM", "지정 멤버가 팀에 없습니다."); }
      if (target.targetType === "ROLE") { if (!target.targetRoleId || target.targetMemberId) throw new ApiError(HttpStatus.BAD_REQUEST, "INVALID_REQUEST", "역할 대상 형식이 올바르지 않습니다."); const role = await this.relay.db.teamRole.findUnique({ where: { id: target.targetRoleId } }); if (!role || role.teamId !== teamId || !role.isActive) throw new ApiError(HttpStatus.BAD_REQUEST, "INVALID_REQUEST", "지정 역할을 찾을 수 없습니다."); }
    }
  }

  @Get("teams") async teams(@Req() req: RequestWithUser) { return { data: await this.relay.listTeams(this.user(req)) }; }
  @Post("teams") async createTeam(@Req() req: RequestWithUser, @Body() body: unknown) { const data = parse(z.object({ name: z.string().min(1).max(60), description: z.string().max(300).optional() }), body); return { data: await this.relay.createTeam(this.user(req), data.name, data.description) }; }
  @Get("teams/:teamId") async team(@Req() req: RequestWithUser, @Param("teamId") teamId: string) { await this.relay.member(teamId, this.user(req)); const team = await this.relay.db.team.findUnique({ where: { id: teamId } }); if (!team) throw new ApiError(HttpStatus.NOT_FOUND, "TEAM_NOT_FOUND", "팀을 찾을 수 없습니다."); return { data: team }; }
  @Patch("teams/:teamId") async updateTeam(@Req() req: RequestWithUser, @Param("teamId") teamId: string, @Body() body: unknown) { const member = await this.relay.member(teamId, this.user(req)); this.relay.require(member, "TEAM_SETTINGS_UPDATE"); const data = parse(z.object({ name: z.string().min(1).max(60).optional(), description: z.string().max(300).nullable().optional() }), body); return { data: await this.relay.db.team.update({ where: { id: teamId }, data }) }; }
  @Get("teams/:teamId/home") async home(@Req() req: RequestWithUser, @Param("teamId") teamId: string) { return { data: await this.relay.home(teamId, this.user(req)) }; }
  @Get("teams/:teamId/members") async members(@Req() req: RequestWithUser, @Param("teamId") teamId: string) { await this.relay.member(teamId, this.user(req)); return { data: await this.relay.db.teamMember.findMany({ where: { teamId, isActive: true }, include: { user: true, roles: { include: { role: true } } } }) }; }
  @Post("teams/:teamId/members") async addMember(@Req() req: RequestWithUser, @Param("teamId") teamId: string, @Body() body: unknown) { const member = await this.relay.member(teamId, this.user(req)); this.relay.require(member, "MEMBER_INVITE"); const { userId } = parse(z.object({ userId: z.string() }), body); const user = await this.relay.db.user.findUnique({ where: { id: userId } }); if (!user) throw new ApiError(HttpStatus.NOT_FOUND, "USER_NOT_FOUND", "사용자를 찾을 수 없습니다."); const data = await this.relay.db.teamMember.upsert({ where: { teamId_userId: { teamId, userId } }, create: { teamId, userId }, update: { isActive: true, leftAt: null } }); return { data }; }
  @Delete("teams/:teamId/members/:memberId") async removeMember(@Req() req: RequestWithUser, @Param("teamId") teamId: string, @Param("memberId") memberId: string) { const member = await this.relay.member(teamId, this.user(req)); this.relay.require(member, "MEMBER_REMOVE"); const target = await this.relay.db.teamMember.findUnique({ where: { id: memberId } }); if (!target || target.teamId !== teamId || target.isOwner) throw new ApiError(HttpStatus.BAD_REQUEST, "INVALID_MEMBER", "제외할 수 없는 멤버입니다."); await this.relay.db.teamMember.update({ where: { id: memberId }, data: { isActive: false, leftAt: new Date() } }); return { data: { memberId, isActive: false } }; }

  @Get("teams/:teamId/categories") async categories(@Req() req: RequestWithUser, @Param("teamId") teamId: string) { await this.relay.member(teamId, this.user(req)); return { data: await this.relay.db.teamCategory.findMany({ where: { teamId }, orderBy: { sortOrder: "asc" } }) }; }
  @Post("teams/:teamId/categories") async createCategory(@Req() req: RequestWithUser, @Param("teamId") teamId: string, @Body() body: unknown) { const member = await this.relay.member(teamId, this.user(req)); this.relay.require(member, "CATEGORY_MANAGE"); const data = parse(z.object({ name: z.string().min(1).max(30), sortOrder: z.number().int().min(0).optional() }), body); return { data: await this.relay.db.teamCategory.create({ data: { teamId, name: data.name, sortOrder: data.sortOrder ?? 99 } }) }; }
  @Patch("teams/:teamId/categories/:categoryId") async updateCategory(@Req() req: RequestWithUser, @Param("teamId") teamId: string, @Param("categoryId") categoryId: string, @Body() body: unknown) { const member = await this.relay.member(teamId, this.user(req)); this.relay.require(member, "CATEGORY_MANAGE"); const category = await this.relay.db.teamCategory.findUnique({ where: { id: categoryId } }); if (!category || category.teamId !== teamId) throw new ApiError(HttpStatus.NOT_FOUND, "CATEGORY_NOT_FOUND", "카테고리를 찾을 수 없습니다."); const data = parse(z.object({ name: z.string().min(1).max(30).optional(), sortOrder: z.number().int().min(0).optional(), isActive: z.boolean().optional() }), body); return { data: await this.relay.db.teamCategory.update({ where: { id: categoryId }, data }) }; }
  @Delete("teams/:teamId/categories/:categoryId") async deactivateCategory(@Req() req: RequestWithUser, @Param("teamId") teamId: string, @Param("categoryId") categoryId: string) { const member = await this.relay.member(teamId, this.user(req)); this.relay.require(member, "CATEGORY_MANAGE"); const category = await this.relay.db.teamCategory.findUnique({ where: { id: categoryId } }); if (!category || category.teamId !== teamId) throw new ApiError(HttpStatus.NOT_FOUND, "CATEGORY_NOT_FOUND", "카테고리를 찾을 수 없습니다."); return { data: await this.relay.db.teamCategory.update({ where: { id: categoryId }, data: { isActive: false } }) }; }

  @Get("teams/:teamId/roles") async roles(@Req() req: RequestWithUser, @Param("teamId") teamId: string) { await this.relay.member(teamId, this.user(req)); const roles = await this.relay.db.teamRole.findMany({ where: { teamId }, orderBy: { name: "asc" } }); return { data: roles.map((role) => ({ ...role, permissions: JSON.parse(role.permissions) })) }; }
  @Post("teams/:teamId/roles") async createRole(@Req() req: RequestWithUser, @Param("teamId") teamId: string, @Body() body: unknown) { await this.owner(teamId, this.user(req)); const data = parse(z.object({ name: z.string().min(1).max(30), permissions: z.array(z.enum(["TEAM_SETTINGS_UPDATE", "MEMBER_INVITE", "MEMBER_REMOVE", "CATEGORY_MANAGE", "ITEM_UPDATE_ANY"])) }), body); return { data: await this.relay.db.teamRole.create({ data: { teamId, name: data.name, permissions: JSON.stringify(data.permissions) } }) }; }
  @Patch("teams/:teamId/roles/:roleId") async updateRole(@Req() req: RequestWithUser, @Param("teamId") teamId: string, @Param("roleId") roleId: string, @Body() body: unknown) { await this.owner(teamId, this.user(req)); const role = await this.relay.db.teamRole.findUnique({ where: { id: roleId } }); if (!role || role.teamId !== teamId) throw new ApiError(HttpStatus.NOT_FOUND, "ROLE_NOT_FOUND", "역할을 찾을 수 없습니다."); const data = parse(z.object({ name: z.string().min(1).max(30).optional(), permissions: z.array(z.enum(["TEAM_SETTINGS_UPDATE", "MEMBER_INVITE", "MEMBER_REMOVE", "CATEGORY_MANAGE", "ITEM_UPDATE_ANY"])).optional(), isActive: z.boolean().optional() }), body); return { data: await this.relay.db.teamRole.update({ where: { id: roleId }, data: { name: data.name, isActive: data.isActive, permissions: data.permissions ? JSON.stringify(data.permissions) : undefined } }) }; }
  @Delete("teams/:teamId/roles/:roleId") async deactivateRole(@Req() req: RequestWithUser, @Param("teamId") teamId: string, @Param("roleId") roleId: string) { await this.owner(teamId, this.user(req)); const role = await this.relay.db.teamRole.findUnique({ where: { id: roleId } }); if (!role || role.teamId !== teamId) throw new ApiError(HttpStatus.NOT_FOUND, "ROLE_NOT_FOUND", "역할을 찾을 수 없습니다."); return { data: await this.relay.db.teamRole.update({ where: { id: roleId }, data: { isActive: false } }) }; }
  @Patch("teams/:teamId/members/:memberId/roles") async setRoles(@Req() req: RequestWithUser, @Param("teamId") teamId: string, @Param("memberId") memberId: string, @Body() body: unknown) { await this.owner(teamId, this.user(req)); const { roleIds } = parse(z.object({ roleIds: z.array(z.string()) }), body); const target = await this.relay.db.teamMember.findUnique({ where: { id: memberId } }); if (!target || target.teamId !== teamId || target.isOwner) throw new ApiError(HttpStatus.BAD_REQUEST, "INVALID_MEMBER", "역할을 변경할 수 없는 멤버입니다."); const count = await this.relay.db.teamRole.count({ where: { id: { in: roleIds }, teamId, isActive: true } }); if (count !== roleIds.length) throw new ApiError(HttpStatus.BAD_REQUEST, "INVALID_ROLE", "팀 역할만 부여할 수 있습니다."); await this.relay.db.$transaction([this.relay.db.teamMemberRole.deleteMany({ where: { teamMemberId: memberId } }), this.relay.db.teamMemberRole.createMany({ data: roleIds.map((roleId) => ({ teamMemberId: memberId, roleId })) })]); return { data: { memberId, roleIds } }; }

  @Get("teams/:teamId/items") async items(@Req() req: RequestWithUser, @Param("teamId") teamId: string, @Query() query: unknown) { const member = await this.relay.member(teamId, this.user(req)); return this.relay.listItems(teamId, member, parse(itemListQuerySchema, query)); }
  @Post("teams/:teamId/items") async createItem(@Req() req: RequestWithUser, @Param("teamId") teamId: string, @Body() body: unknown) { const member = await this.relay.member(teamId, this.user(req)); const data = parse(createItemSchema, body); const category = await this.relay.db.teamCategory.findUnique({ where: { id: data.categoryId } }); if (!category || category.teamId !== teamId || !category.isActive) throw new ApiError(HttpStatus.BAD_REQUEST, "INVALID_CATEGORY", "사용할 수 없는 카테고리입니다."); await this.assertAudiences(teamId, data.audiences, data.audienceType); const item = await this.relay.db.item.create({ data: { teamId, categoryId: data.categoryId, authorMemberId: member.id, title: data.title, content: data.content, isImportant: data.isImportant, audienceType: data.audienceType, requiresCompletion: data.requiresCompletion, completionStatus: data.requiresCompletion ? CompletionStatus.INCOMPLETE : null, audiences: { create: data.audiences.map((target) => ({ targetType: target.targetType, targetMemberId: target.targetMemberId, targetRoleId: target.targetRoleId })) } }, include: { category: true, author: { include: { user: true } }, audiences: true, reads: true } }); return { data: this.relay.summary(item) }; }
  @Get("items/:itemId") async item(@Req() req: RequestWithUser, @Param("itemId") itemId: string) { const { item, member } = await this.relay.visibleItem(itemId, this.user(req)); const read = await this.relay.db.itemRead.findUnique({ where: { itemId_teamMemberId: { itemId, teamMemberId: member.id } } }); if (!read) await this.relay.db.itemRead.create({ data: { itemId, teamMemberId: member.id } }); const reads = await this.relay.db.itemRead.findMany({ where: { itemId }, include: { teamMember: { include: { user: true } } } }); return { data: { ...this.relay.summary({ ...item, reads: read ? [read] : [] }), content: item.content, audiences: item.audiences, reads: reads.map((entry) => ({ memberId: entry.teamMemberId, name: entry.teamMember.user.name, readAt: entry.readAt })) } }; }
  @Patch("items/:itemId") async updateItem(@Req() req: RequestWithUser, @Param("itemId") itemId: string, @Body() body: unknown) { const { item, member } = await this.relay.visibleItem(itemId, this.user(req)); if (item.authorMemberId !== member.id) this.relay.require(member, "ITEM_UPDATE_ANY"); const data = parse(updateItemSchema, body); if (data.categoryId) { const category = await this.relay.db.teamCategory.findUnique({ where: { id: data.categoryId } }); if (!category || category.teamId !== item.teamId) throw new ApiError(HttpStatus.BAD_REQUEST, "INVALID_CATEGORY", "사용할 수 없는 카테고리입니다."); }
    if (data.audienceType || data.audiences) await this.assertAudiences(item.teamId, data.audiences ?? item.audiences.map((a) => ({ targetType: a.targetType, targetMemberId: a.targetMemberId ?? undefined, targetRoleId: a.targetRoleId ?? undefined })), data.audienceType ?? item.audienceType);
    const updated = await this.relay.db.$transaction(async (tx) => { if (data.audiences) await tx.itemAudience.deleteMany({ where: { itemId } }); return tx.item.update({ where: { id: itemId }, data: { title: data.title, content: data.content, categoryId: data.categoryId, isImportant: data.isImportant, audienceType: data.audienceType, requiresCompletion: data.requiresCompletion, completionStatus: data.requiresCompletion === false ? null : data.requiresCompletion === true && !item.requiresCompletion ? CompletionStatus.INCOMPLETE : undefined, ...(data.audiences ? { audiences: { create: data.audiences.map((target) => ({ targetType: target.targetType, targetMemberId: target.targetMemberId, targetRoleId: target.targetRoleId })) } } : {}) }, include: { category: true, author: { include: { user: true } }, audiences: true, reads: { where: { teamMemberId: member.id } } } }); }); return { data: this.relay.summary(updated) }; }
  @Delete("items/:itemId") @HttpCode(HttpStatus.NO_CONTENT) async deleteItem(@Req() req: RequestWithUser, @Param("itemId") itemId: string) { const { item, member } = await this.relay.visibleItem(itemId, this.user(req)); if (item.authorMemberId !== member.id) this.relay.require(member, "ITEM_UPDATE_ANY"); await this.relay.db.item.delete({ where: { id: item.id } }); }
  @Patch("items/:itemId/completion") async completion(@Req() req: RequestWithUser, @Param("itemId") itemId: string, @Body() body: unknown) { const { item } = await this.relay.visibleItem(itemId, this.user(req)); if (!item.requiresCompletion) throw new ApiError(HttpStatus.BAD_REQUEST, "INVALID_ITEM_STATE", "처리 완료 관리가 켜진 전달사항만 상태를 변경할 수 있습니다."); const { completionStatus } = parse(z.object({ completionStatus: z.nativeEnum(CompletionStatus) }), body); return { data: await this.relay.db.item.update({ where: { id: itemId }, data: { completionStatus } }) }; }
  @Post("items/:itemId/read") async read(@Req() req: RequestWithUser, @Param("itemId") itemId: string) { const { member } = await this.relay.visibleItem(itemId, this.user(req)); const data = await this.relay.db.itemRead.upsert({ where: { itemId_teamMemberId: { itemId, teamMemberId: member.id } }, create: { itemId, teamMemberId: member.id }, update: {} }); return { data: { readAt: data.readAt } }; }
  @Get("items/:itemId/reads") async reads(@Req() req: RequestWithUser, @Param("itemId") itemId: string) { await this.relay.visibleItem(itemId, this.user(req)); const data = await this.relay.db.itemRead.findMany({ where: { itemId }, include: { teamMember: { include: { user: true } } } }); return { data: data.map((entry) => ({ memberId: entry.teamMemberId, name: entry.teamMember.user.name, readAt: entry.readAt })) }; }
}
